/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSupplierDto,
  HttpConflictResponse,
  HttpNotFoundResponse,
  SupplierResponse,
  UpdateSupplierDto
} from '../models';

import { axiosInstance } from '../../axios';
import type { ErrorType , BodyType } from '../../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Razão social, CNPJ, endereço; telefones opcionais (11 dígitos).
 * @summary Cadastra fornecedor
 */
export const suppliersControllerCreate = (
    createSupplierDto: BodyType<CreateSupplierDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SupplierResponse>(
      {url: `/suppliers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSupplierDto, signal
    },
      options);
    }



export const getSuppliersControllerCreateMutationOptions = <TError = ErrorType<void | HttpConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerCreate>>, TError,{data: BodyType<CreateSupplierDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerCreate>>, TError,{data: BodyType<CreateSupplierDto>}, TContext> => {

const mutationKey = ['suppliersControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suppliersControllerCreate>>, {data: BodyType<CreateSupplierDto>}> = (props) => {
          const {data} = props ?? {};

          return  suppliersControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SuppliersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof suppliersControllerCreate>>>
    export type SuppliersControllerCreateMutationBody = BodyType<CreateSupplierDto>
    export type SuppliersControllerCreateMutationError = ErrorType<void | HttpConflictResponse>

    /**
 * @summary Cadastra fornecedor
 */
export const useSuppliersControllerCreate = <TError = ErrorType<void | HttpConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerCreate>>, TError,{data: BodyType<CreateSupplierDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suppliersControllerCreate>>,
        TError,
        {data: BodyType<CreateSupplierDto>},
        TContext
      > => {
      return useMutation(getSuppliersControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Lista fornecedores
 */
export const suppliersControllerFindAll = (

 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SupplierResponse[]>(
      {url: `/suppliers`, method: 'GET', signal
    },
      options);
    }




export const getSuppliersControllerFindAllQueryKey = () => {
    return [
    `/suppliers`
    ] as const;
    }


export const getSuppliersControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSuppliersControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof suppliersControllerFindAll>>> = ({ signal }) => suppliersControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SuppliersControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof suppliersControllerFindAll>>>
export type SuppliersControllerFindAllQueryError = ErrorType<unknown>


export function useSuppliersControllerFindAll<TData = Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof suppliersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSuppliersControllerFindAll<TData = Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof suppliersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSuppliersControllerFindAll<TData = Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista fornecedores
 */

export function useSuppliersControllerFindAll<TData = Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSuppliersControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Obtém fornecedor por id
 */
export const suppliersControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SupplierResponse>(
      {url: `/suppliers/${id}`, method: 'GET', signal
    },
      options);
    }




export const getSuppliersControllerFindOneQueryKey = (id: string,) => {
    return [
    `/suppliers/${id}`
    ] as const;
    }


export const getSuppliersControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSuppliersControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof suppliersControllerFindOne>>> = ({ signal }) => suppliersControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SuppliersControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof suppliersControllerFindOne>>>
export type SuppliersControllerFindOneQueryError = ErrorType<HttpNotFoundResponse>


export function useSuppliersControllerFindOne<TData = Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof suppliersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSuppliersControllerFindOne<TData = Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof suppliersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSuppliersControllerFindOne<TData = Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtém fornecedor por id
 */

export function useSuppliersControllerFindOne<TData = Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSuppliersControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * CNPJ não pode ser alterado por este endpoint.
 * @summary Atualiza fornecedor
 */
export const suppliersControllerUpdate = (
    id: string,
    updateSupplierDto: BodyType<UpdateSupplierDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SupplierResponse>(
      {url: `/suppliers/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSupplierDto, signal
    },
      options);
    }



export const getSuppliersControllerUpdateMutationOptions = <TError = ErrorType<void | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerUpdate>>, TError,{id: string;data: BodyType<UpdateSupplierDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerUpdate>>, TError,{id: string;data: BodyType<UpdateSupplierDto>}, TContext> => {

const mutationKey = ['suppliersControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suppliersControllerUpdate>>, {id: string;data: BodyType<UpdateSupplierDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  suppliersControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SuppliersControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof suppliersControllerUpdate>>>
    export type SuppliersControllerUpdateMutationBody = BodyType<UpdateSupplierDto>
    export type SuppliersControllerUpdateMutationError = ErrorType<void | HttpNotFoundResponse>

    /**
 * @summary Atualiza fornecedor
 */
export const useSuppliersControllerUpdate = <TError = ErrorType<void | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerUpdate>>, TError,{id: string;data: BodyType<UpdateSupplierDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suppliersControllerUpdate>>,
        TError,
        {id: string;data: BodyType<UpdateSupplierDto>},
        TContext
      > => {
      return useMutation(getSuppliersControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove fornecedor
 */
export const suppliersControllerRemove = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SupplierResponse>(
      {url: `/suppliers/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getSuppliersControllerRemoveMutationOptions = <TError = ErrorType<HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['suppliersControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suppliersControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  suppliersControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SuppliersControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof suppliersControllerRemove>>>

    export type SuppliersControllerRemoveMutationError = ErrorType<HttpNotFoundResponse>

    /**
 * @summary Remove fornecedor
 */
export const useSuppliersControllerRemove = <TError = ErrorType<HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suppliersControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getSuppliersControllerRemoveMutationOptions(options), queryClient);
    }
