/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Easy Óleo — API de distribuição de óleo automotivo. Schemas gerados a partir dos DTOs Zod; consumo no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

export interface CreateProductDto {
  /**
     * Código único do produto.
     * @minLength 1
     */
  code: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  brand: string;
  /** @minLength 1 */
  type: string;
  viscosity?: string;
  /** @minLength 1 */
  unit: string;
  /** @exclusiveMinimum 0 */
  salePrice: number;
  /**
     * @minimum 0
     * @nullable
     */
  stockQuantity: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  minStock: number | null;
}
