/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

export interface CreateSupplierDto {
  /**
     * Razão social do fornecedor.
     * @minLength 1
     * @maxLength 300
     */
  legalName: string;
  /**
     * CNPJ com 14 dígitos e dígitos verificadores válidos, só números.
     * @pattern ^\d{14}$
     */
  cnpj: string;
  /**
     * Logradouro.
     * @minLength 1
     */
  street: string;
  /**
     * Número ou referência.
     * @minLength 1
     */
  number: string;
  /** Complemento. */
  complement?: string;
  /** Bairro ou distrito. */
  district?: string;
  /**
     * Cidade.
     * @minLength 1
     */
  city: string;
  /**
     * UF (2 letras).
     * @minLength 2
     * @maxLength 2
     */
  state: string;
  /**
     * CEP.
     * @minLength 8
     * @maxLength 9
     */
  zipCode: string;
  /** E-mail comercial. */
  email: string;
  /** Telefones com DDD (11 dígitos). */
  phones?: string[];
}
