/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { CreatePurchaseOrderDtoItemsItem } from './createPurchaseOrderDtoItemsItem';

export interface CreatePurchaseOrderDto {
  /** @nullable */
  purchaseDate?: string | null;
  /** @minLength 1 */
  supplierId: string;
  /** @minLength 1 */
  registeredByUserId: string;
  /**
     * Ao registrar a compra, o estoque dos produtos é incrementado.
     * @minItems 1
     */
  items: CreatePurchaseOrderDtoItemsItem[];
}
