/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Easy Óleo — API de distribuição de óleo automotivo. Schemas gerados a partir dos DTOs Zod; consumo no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

/**
 * Pessoa física ou jurídica. Se omitido, usa PF.
 */
export type CreateCustomerDtoType = typeof CreateCustomerDtoType[keyof typeof CreateCustomerDtoType];


export const CreateCustomerDtoType = {
  PF: 'PF',
  PJ: 'PJ',
} as const;
