/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  /** @minLength 1 */
  name: string;
  /**
     * CPF com 11 dígitos e dígitos verificadores válidos.
     * @pattern ^\d{11}$
     */
  cpf: string;
  /** @minLength 1 */
  street: string;
  /** @minLength 1 */
  number: string;
  complement?: string;
  district?: string;
  /** @minLength 1 */
  city: string;
  /**
     * @minLength 2
     * @maxLength 2
     */
  state: string;
  /** @minLength 8 */
  zipCode: string;
  email: string;
  role?: CreateUserDtoRole;
  phones?: string[];
}
