/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Easy Óleo — API de distribuição de óleo automotivo. Schemas gerados a partir dos DTOs Zod; consumo no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  /** @minLength 1 */
  name: string;
  /** @pattern ^\d{11}$ */
  cpf: string;
  /** @minLength 1 */
  street: string;
  /** @minLength 1 */
  number: string;
  complement?: string;
  district?: string;
  /** @minLength 1 */
  city: string;
  /**
     * @minLength 2
     * @maxLength 2
     */
  state: string;
  /** @minLength 8 */
  zipCode: string;
  email: string;
  /**
     * Senha em texto; armazenada com hash.
     * @minLength 8
     * @maxLength 72
     */
  password: string;
  role?: CreateUserDtoRole;
  phones?: string[];
}
