/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Easy Óleo — API de distribuição de óleo automotivo. Schemas gerados a partir dos DTOs Zod; consumo no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

export interface CustomerPhoneResponse {
  /** Identificador do telefone. */
  id: string;
  /** Telefone com DDD, 11 dígitos. */
  number: string;
}
