/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

/**
 * Tipo de pessoa.
 */
export type CustomerResponseType = typeof CustomerResponseType[keyof typeof CustomerResponseType];


export const CustomerResponseType = {
  PF: 'PF',
  PJ: 'PJ',
} as const;
