/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Easy Óleo — API de distribuição de óleo automotivo. Schemas gerados a partir dos DTOs Zod; consumo no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { CustomerPhoneResponse } from './customerPhoneResponse';
import type { CustomerResponseType } from './customerResponseType';

export interface CustomerResponse {
  /** Identificador único (CUID). */
  id: string;
  /** Tipo de pessoa. */
  type: CustomerResponseType;
  /** Nome (PF) ou razão social (PJ). */
  name: string;
  /** CPF (11 dígitos) ou CNPJ (14 dígitos), apenas números. */
  document: string;
  /** Logradouro. */
  street: string;
  /** Número. */
  number: string;
  /**
     * Complemento.
     * @nullable
     */
  complement?: string | null;
  /**
     * Bairro.
     * @nullable
     */
  district?: string | null;
  /** Município. */
  city: string;
  /** UF (2 letras). */
  state: string;
  /** CEP (somente números ou formatado conforme cadastro). */
  zipCode: string;
  /** E-mail de contato. */
  email: string;
  /** Telefones cadastrados. */
  phones: CustomerPhoneResponse[];
  /** Data de criação do registro. */
  createdAt: string;
  /** Data da última atualização. */
  updatedAt: string;
}
