/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

export interface HttpBadRequestResponse {
  /** Código HTTP. */
  statusCode: number;
  /** Mensagem explicando a regra de negócio ou validação. */
  message: string;
  /** Rótulo do erro HTTP. */
  error: string;
}
