/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { HttpConflictResponseMessage } from './httpConflictResponseMessage';

export interface HttpConflictResponse {
  /** Código HTTP. */
  statusCode: number;
  /** Mensagem explicando o conflito. */
  message: HttpConflictResponseMessage;
  /** Rótulo do erro HTTP. */
  error: string;
}
