/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Easy Óleo — API de distribuição de óleo automotivo. Schemas gerados a partir dos DTOs Zod; consumo no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

export interface HttpNotFoundResponse {
  /** Código HTTP. */
  statusCode: number;
  /** Mensagem explicando o recurso ausente. */
  message: string;
  /** Rótulo do erro HTTP. */
  error: string;
}
