/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Easy Óleo — API de distribuição de óleo automotivo. Schemas gerados a partir dos DTOs Zod; consumo no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { PurchaseOrderItemResponse } from './purchaseOrderItemResponse';
import type { PurchaseOrderPartyResponse } from './purchaseOrderPartyResponse';

export interface PurchaseOrderResponse {
  id: string;
  purchaseDate: string;
  total: number;
  supplier: PurchaseOrderPartyResponse;
  registeredBy: PurchaseOrderPartyResponse;
  items: PurchaseOrderItemResponse[];
  createdAt: string;
  updatedAt: string;
}
