/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { SaleOrderItemResponse } from './saleOrderItemResponse';
import type { SaleOrderPartyResponse } from './saleOrderPartyResponse';
import type { SaleOrderResponseStatus } from './saleOrderResponseStatus';

export interface SaleOrderResponse {
  id: string;
  orderDate: string;
  total: number;
  status: SaleOrderResponseStatus;
  customer: SaleOrderPartyResponse;
  createdBy: SaleOrderPartyResponse;
  items: SaleOrderItemResponse[];
  createdAt: string;
  updatedAt: string;
}
