/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { SupplierPhoneResponse } from './supplierPhoneResponse';

export interface SupplierResponse {
  /** Identificador único (CUID). */
  id: string;
  /** Razão social. */
  legalName: string;
  /** CNPJ com 14 dígitos e dígitos verificadores válidos. */
  cnpj: string;
  /** Logradouro. */
  street: string;
  /** Número. */
  number: string;
  /**
     * Complemento.
     * @nullable
     */
  complement?: string | null;
  /**
     * Bairro / distrito.
     * @nullable
     */
  district?: string | null;
  /** Município. */
  city: string;
  /** UF (2 letras). */
  state: string;
  /** CEP. */
  zipCode: string;
  /** E-mail comercial. */
  email: string;
  /** Telefones cadastrados. */
  phones: SupplierPhoneResponse[];
  /** Data de criação do registro. */
  createdAt: string;
  /** Data da última atualização. */
  updatedAt: string;
}
