/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { UpdateCustomerDtoType } from './updateCustomerDtoType';

export interface UpdateCustomerDto {
  /** Pessoa física ou jurídica. Se omitido, usa PF. */
  type?: UpdateCustomerDtoType;
  /**
     * Nome (PF) ou razão social (PJ).
     * @minLength 1
     * @maxLength 300
     */
  name?: string;
  /**
     * Logradouro.
     * @minLength 1
     */
  street?: string;
  /**
     * Número.
     * @minLength 1
     */
  number?: string;
  /** Complemento. */
  complement?: string;
  /** Bairro. */
  district?: string;
  /**
     * Cidade.
     * @minLength 1
     */
  city?: string;
  /**
     * UF (2 letras).
     * @minLength 2
     * @maxLength 2
     */
  state?: string;
  /**
     * CEP.
     * @minLength 8
     * @maxLength 9
     */
  zipCode?: string;
  /** E-mail de contato. */
  email?: string;
  /** Telefones com DDD (11 dígitos, somente números). */
  phones?: string[];
}
