/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Easy Óleo — API de distribuição de óleo automotivo. Schemas gerados a partir dos DTOs Zod; consumo no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

export interface UpdateSupplierDto {
  /**
     * Razão social do fornecedor.
     * @minLength 1
     * @maxLength 300
     */
  legalName?: string;
  /**
     * Logradouro.
     * @minLength 1
     */
  street?: string;
  /**
     * Número ou referência.
     * @minLength 1
     */
  number?: string;
  /** Complemento. */
  complement?: string;
  /** Bairro ou distrito. */
  district?: string;
  /**
     * Cidade.
     * @minLength 1
     */
  city?: string;
  /**
     * UF (2 letras).
     * @minLength 2
     * @maxLength 2
     */
  state?: string;
  /**
     * CEP.
     * @minLength 8
     * @maxLength 9
     */
  zipCode?: string;
  /** E-mail comercial. */
  email?: string;
  /** Telefones com DDD (11 dígitos). */
  phones?: string[];
}
