/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { UpdateSaleOrderDtoItemsItem } from './updateSaleOrderDtoItemsItem';

export interface UpdateSaleOrderDto {
  /**
     * Data do pedido; default agora.
     * @nullable
     */
  orderDate?: string | null;
  /** @minLength 1 */
  customerId?: string;
  /** @minItems 1 */
  items?: UpdateSaleOrderDtoItemsItem[];
}
