/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoRole } from './updateUserDtoRole';

export interface UpdateUserDto {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  street?: string;
  /** @minLength 1 */
  number?: string;
  complement?: string;
  district?: string;
  /** @minLength 1 */
  city?: string;
  /**
     * @minLength 2
     * @maxLength 2
     */
  state?: string;
  /** @minLength 8 */
  zipCode?: string;
  email?: string;
  role?: UpdateUserDtoRole;
  phones?: string[];
  /**
     * Nova senha (opcional).
     * @minLength 8
     * @maxLength 72
     */
  password?: string;
}
