/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */

export interface UpdateProductDto {
  /**
     * Código único do produto.
     * @minLength 1
     */
  code?: string;
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  brand?: string;
  /** @minLength 1 */
  type?: string;
  viscosity?: string;
  /** @minLength 1 */
  unit?: string;
  /** @exclusiveMinimum 0 */
  salePrice?: number;
  /**
     * @minimum 0
     * @nullable
     */
  stockQuantity?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  minStock?: number | null;
}
