/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import type { UserPhoneResponse } from './userPhoneResponse';
import type { UserResponseRole } from './userResponseRole';

export interface UserResponse {
  id: string;
  name: string;
  /** CPF com 11 dígitos e dígitos verificadores válidos. */
  cpf: string;
  street: string;
  number: string;
  /** @nullable */
  complement?: string | null;
  /** @nullable */
  district?: string | null;
  city: string;
  state: string;
  zipCode: string;
  email: string;
  role: UserResponseRole;
  phones: UserPhoneResponse[];
  createdAt: string;
  updatedAt: string;
}
