/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSaleOrderDto,
  HttpBadRequestResponse,
  HttpNotFoundResponse,
  SaleOrderResponse,
  UpdateSaleOrderDto
} from '../models';

import { axiosInstance } from '../../axios';
import type { ErrorType , BodyType } from '../../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Status inicial DRAFT. Preço unitário de cada linha é o salePrice atual do produto.
 * @summary Cadastra pedido de venda
 */
export const saleOrdersControllerCreate = (
    createSaleOrderDto: BodyType<CreateSaleOrderDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SaleOrderResponse>(
      {url: `/sale-orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSaleOrderDto, signal
    },
      options);
    }



export const getSaleOrdersControllerCreateMutationOptions = <TError = ErrorType<void | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerCreate>>, TError,{data: BodyType<CreateSaleOrderDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerCreate>>, TError,{data: BodyType<CreateSaleOrderDto>}, TContext> => {

const mutationKey = ['saleOrdersControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saleOrdersControllerCreate>>, {data: BodyType<CreateSaleOrderDto>}> = (props) => {
          const {data} = props ?? {};

          return  saleOrdersControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaleOrdersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof saleOrdersControllerCreate>>>
    export type SaleOrdersControllerCreateMutationBody = BodyType<CreateSaleOrderDto>
    export type SaleOrdersControllerCreateMutationError = ErrorType<void | HttpNotFoundResponse>

    /**
 * @summary Cadastra pedido de venda
 */
export const useSaleOrdersControllerCreate = <TError = ErrorType<void | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerCreate>>, TError,{data: BodyType<CreateSaleOrderDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saleOrdersControllerCreate>>,
        TError,
        {data: BodyType<CreateSaleOrderDto>},
        TContext
      > => {
      return useMutation(getSaleOrdersControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Lista pedidos de venda
 */
export const saleOrdersControllerFindAll = (

 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SaleOrderResponse[]>(
      {url: `/sale-orders`, method: 'GET', signal
    },
      options);
    }




export const getSaleOrdersControllerFindAllQueryKey = () => {
    return [
    `/sale-orders`
    ] as const;
    }


export const getSaleOrdersControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSaleOrdersControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof saleOrdersControllerFindAll>>> = ({ signal }) => saleOrdersControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SaleOrdersControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof saleOrdersControllerFindAll>>>
export type SaleOrdersControllerFindAllQueryError = ErrorType<unknown>


export function useSaleOrdersControllerFindAll<TData = Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof saleOrdersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof saleOrdersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSaleOrdersControllerFindAll<TData = Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof saleOrdersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof saleOrdersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSaleOrdersControllerFindAll<TData = Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista pedidos de venda
 */

export function useSaleOrdersControllerFindAll<TData = Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSaleOrdersControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Obtém pedido por id
 */
export const saleOrdersControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SaleOrderResponse>(
      {url: `/sale-orders/${id}`, method: 'GET', signal
    },
      options);
    }




export const getSaleOrdersControllerFindOneQueryKey = (id: string,) => {
    return [
    `/sale-orders/${id}`
    ] as const;
    }


export const getSaleOrdersControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSaleOrdersControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof saleOrdersControllerFindOne>>> = ({ signal }) => saleOrdersControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SaleOrdersControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof saleOrdersControllerFindOne>>>
export type SaleOrdersControllerFindOneQueryError = ErrorType<HttpNotFoundResponse>


export function useSaleOrdersControllerFindOne<TData = Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof saleOrdersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof saleOrdersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSaleOrdersControllerFindOne<TData = Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof saleOrdersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof saleOrdersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSaleOrdersControllerFindOne<TData = Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtém pedido por id
 */

export function useSaleOrdersControllerFindOne<TData = Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof saleOrdersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSaleOrdersControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Se enviar items, substitui todos os itens e recalcula o total.
 * @summary Atualiza pedido (somente DRAFT)
 */
export const saleOrdersControllerUpdate = (
    id: string,
    updateSaleOrderDto: BodyType<UpdateSaleOrderDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SaleOrderResponse>(
      {url: `/sale-orders/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSaleOrderDto, signal
    },
      options);
    }



export const getSaleOrdersControllerUpdateMutationOptions = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerUpdate>>, TError,{id: string;data: BodyType<UpdateSaleOrderDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerUpdate>>, TError,{id: string;data: BodyType<UpdateSaleOrderDto>}, TContext> => {

const mutationKey = ['saleOrdersControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saleOrdersControllerUpdate>>, {id: string;data: BodyType<UpdateSaleOrderDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  saleOrdersControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaleOrdersControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof saleOrdersControllerUpdate>>>
    export type SaleOrdersControllerUpdateMutationBody = BodyType<UpdateSaleOrderDto>
    export type SaleOrdersControllerUpdateMutationError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>

    /**
 * @summary Atualiza pedido (somente DRAFT)
 */
export const useSaleOrdersControllerUpdate = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerUpdate>>, TError,{id: string;data: BodyType<UpdateSaleOrderDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saleOrdersControllerUpdate>>,
        TError,
        {id: string;data: BodyType<UpdateSaleOrderDto>},
        TContext
      > => {
      return useMutation(getSaleOrdersControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove pedido (somente DRAFT)
 */
export const saleOrdersControllerRemove = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SaleOrderResponse>(
      {url: `/sale-orders/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getSaleOrdersControllerRemoveMutationOptions = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['saleOrdersControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saleOrdersControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  saleOrdersControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaleOrdersControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof saleOrdersControllerRemove>>>

    export type SaleOrdersControllerRemoveMutationError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>

    /**
 * @summary Remove pedido (somente DRAFT)
 */
export const useSaleOrdersControllerRemove = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saleOrdersControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getSaleOrdersControllerRemoveMutationOptions(options), queryClient);
    }
    /**
 * Baixa estoque conforme quantidades dos itens.
 * @summary Confirma pedido (DRAFT → CONFIRMED)
 */
export const saleOrdersControllerConfirm = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SaleOrderResponse>(
      {url: `/sale-orders/${id}/confirm`, method: 'POST', signal
    },
      options);
    }



export const getSaleOrdersControllerConfirmMutationOptions = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerConfirm>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerConfirm>>, TError,{id: string}, TContext> => {

const mutationKey = ['saleOrdersControllerConfirm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saleOrdersControllerConfirm>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  saleOrdersControllerConfirm(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaleOrdersControllerConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof saleOrdersControllerConfirm>>>

    export type SaleOrdersControllerConfirmMutationError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>

    /**
 * @summary Confirma pedido (DRAFT → CONFIRMED)
 */
export const useSaleOrdersControllerConfirm = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerConfirm>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saleOrdersControllerConfirm>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getSaleOrdersControllerConfirmMutationOptions(options), queryClient);
    }
    /**
 * DRAFT: apenas marca cancelado. CONFIRMED: devolve estoque e marca cancelado.
 * @summary Cancela pedido
 */
export const saleOrdersControllerCancel = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<SaleOrderResponse>(
      {url: `/sale-orders/${id}/cancel`, method: 'POST', signal
    },
      options);
    }



export const getSaleOrdersControllerCancelMutationOptions = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerCancel>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerCancel>>, TError,{id: string}, TContext> => {

const mutationKey = ['saleOrdersControllerCancel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saleOrdersControllerCancel>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  saleOrdersControllerCancel(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaleOrdersControllerCancelMutationResult = NonNullable<Awaited<ReturnType<typeof saleOrdersControllerCancel>>>

    export type SaleOrdersControllerCancelMutationError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>

    /**
 * @summary Cancela pedido
 */
export const useSaleOrdersControllerCancel = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saleOrdersControllerCancel>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saleOrdersControllerCancel>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getSaleOrdersControllerCancelMutationOptions(options), queryClient);
    }
