/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Easy Óleo API
 * Distribuição de óleo automotivo. Os schemas gerados a partir dos DTOs são consumidos no frontend via Orval/OpenAPI.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePurchaseOrderDto,
  HttpBadRequestResponse,
  HttpNotFoundResponse,
  PurchaseOrderResponse
} from '../models';

import { axiosInstance } from '../../axios';
import type { ErrorType , BodyType } from '../../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Incrementa estoque dos produtos na mesma transação do cadastro.
 * @summary Registra compra de reposição
 */
export const purchaseOrdersControllerCreate = (
    createPurchaseOrderDto: BodyType<CreatePurchaseOrderDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<PurchaseOrderResponse>(
      {url: `/purchase-orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPurchaseOrderDto, signal
    },
      options);
    }



export const getPurchaseOrdersControllerCreateMutationOptions = <TError = ErrorType<void | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseOrdersControllerCreate>>, TError,{data: BodyType<CreatePurchaseOrderDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof purchaseOrdersControllerCreate>>, TError,{data: BodyType<CreatePurchaseOrderDto>}, TContext> => {

const mutationKey = ['purchaseOrdersControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purchaseOrdersControllerCreate>>, {data: BodyType<CreatePurchaseOrderDto>}> = (props) => {
          const {data} = props ?? {};

          return  purchaseOrdersControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PurchaseOrdersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof purchaseOrdersControllerCreate>>>
    export type PurchaseOrdersControllerCreateMutationBody = BodyType<CreatePurchaseOrderDto>
    export type PurchaseOrdersControllerCreateMutationError = ErrorType<void | HttpNotFoundResponse>

    /**
 * @summary Registra compra de reposição
 */
export const usePurchaseOrdersControllerCreate = <TError = ErrorType<void | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseOrdersControllerCreate>>, TError,{data: BodyType<CreatePurchaseOrderDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof purchaseOrdersControllerCreate>>,
        TError,
        {data: BodyType<CreatePurchaseOrderDto>},
        TContext
      > => {
      return useMutation(getPurchaseOrdersControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Lista pedidos de compra
 */
export const purchaseOrdersControllerFindAll = (

 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<PurchaseOrderResponse[]>(
      {url: `/purchase-orders`, method: 'GET', signal
    },
      options);
    }




export const getPurchaseOrdersControllerFindAllQueryKey = () => {
    return [
    `/purchase-orders`
    ] as const;
    }


export const getPurchaseOrdersControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPurchaseOrdersControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>> = ({ signal }) => purchaseOrdersControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PurchaseOrdersControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>>
export type PurchaseOrdersControllerFindAllQueryError = ErrorType<unknown>


export function usePurchaseOrdersControllerFindAll<TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseOrdersControllerFindAll<TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseOrdersControllerFindAll<TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista pedidos de compra
 */

export function usePurchaseOrdersControllerFindAll<TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPurchaseOrdersControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Obtém pedido de compra por id
 */
export const purchaseOrdersControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<PurchaseOrderResponse>(
      {url: `/purchase-orders/${id}`, method: 'GET', signal
    },
      options);
    }




export const getPurchaseOrdersControllerFindOneQueryKey = (id: string,) => {
    return [
    `/purchase-orders/${id}`
    ] as const;
    }


export const getPurchaseOrdersControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPurchaseOrdersControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>> = ({ signal }) => purchaseOrdersControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PurchaseOrdersControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>>
export type PurchaseOrdersControllerFindOneQueryError = ErrorType<HttpNotFoundResponse>


export function usePurchaseOrdersControllerFindOne<TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseOrdersControllerFindOne<TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseOrdersControllerFindOne<TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtém pedido de compra por id
 */

export function usePurchaseOrdersControllerFindOne<TData = Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError = ErrorType<HttpNotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseOrdersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPurchaseOrdersControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Estorna a entrada de estoque vinculada ao pedido (transação única).
 * @summary Remove pedido de compra
 */
export const purchaseOrdersControllerRemove = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {


      return axiosInstance<PurchaseOrderResponse>(
      {url: `/purchase-orders/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getPurchaseOrdersControllerRemoveMutationOptions = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseOrdersControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof purchaseOrdersControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['purchaseOrdersControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purchaseOrdersControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  purchaseOrdersControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PurchaseOrdersControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof purchaseOrdersControllerRemove>>>

    export type PurchaseOrdersControllerRemoveMutationError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>

    /**
 * @summary Remove pedido de compra
 */
export const usePurchaseOrdersControllerRemove = <TError = ErrorType<HttpBadRequestResponse | HttpNotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseOrdersControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof purchaseOrdersControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPurchaseOrdersControllerRemoveMutationOptions(options), queryClient);
    }
